# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Team names, titles and social links
people:
- name: Renán Freire
  pic: 1
  position: Ingeniero de Sistemas
  company: Universidad de Cuenca
  resume: Investigación y desarrollo
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: Santiago Gonzalez
  pic: 2
  position: MSc WSBDA
  company: Universidad de Cuenca
  resume: Full Stack Developer & Data Science Engineer
  social:
    - title: twitter
      url: 
    - title: facebook
      url: https://santteegt.github.io
    - title: linkedin
      url: https://www.linkedin.com/in/santteegt/
    - title: github
      url: github.com/santteegt

- name: Oscar Malgiaritta
  pic: 3
  position: Ingeniero de Sistemas
  company: SimpleTech
  resume: Full Stack Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: Travis Pence
  pic: 4
  position: Ingeniero de Sistemas
  company: Freelancer
  resume: Freelancer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Build settings
markdown: kramdown
